### ISSUE TITLE
How to remove Login page

### ISSUE THREAD

**Issue by shivakrishnay** [sasjs/fileuploader#7]
I'm trying to remove the login page by commenting the below piece of code, could you please suggest us.
/*put ' <div class="form" id="login-form">';
put ' <input type="text" id="username" placeholder="Enter username">';
put ' <input type="password" id="password" placeholder="Enter password">';
put ' </div>';
put ' <button id="login" onclick="login()">Log in</button>';*/

**Comment by shivakrishnay** [comment]
I tried many ways to remove the login page but no luck... Can anyone suggest us ?

**Comment by allanbowe** [comment]
Hi @shivakrishnay  - we have implemented a new login flow.  Can you try again please?
