### ISSUE TITLE
Unable to upload more than 100MB of file

### ISSUE THREAD

**Issue by shivakrishnay** [sasjs/fileuploader#9]
Hi Team.

I'm unable to upload the files which is having more than 100 MB but I'm able to upload the files from SAS Studiov successfully. 

And in EVM we have a limit of 2.5 GB which we can send.

Please assist where is the bug.

Thanks,
Shiva

**Comment by allanbowe** [comment]
Hi Shiva,

Can you try opening SASEnvironmentManager in Viya, under `configuration` / `definitions` search for `sas.files` and update the `maxFileSize` property per your requirements?

And please let us know if this fixes your issue.

![image](https://user-images.githubusercontent.com/4420615/128693812-fb60dac5-adcc-4b5f-ba96-af111c505a23.png)

Best,
Allan

**Comment by shivakrishnay** [comment]
thank you for the update and can we go with the 5 GB or we are having any limitation to upload the file from app,

**Comment by allanbowe** [comment]
There is no limitation in the fileuploader app - other than, perhaps, the amount of memory on your local machine.  The limitation is on the server (SAS) side and is an administrative setting.

If you would like to use 5GB, you can try entering the following value: `5,368,709,120`

Do let us know if this is successful for you.

**Comment by shivakrishnay** [comment]
I changed the value to 2GB in sas.files under configuration / definitions but no luck, even 100 mb of file also not uploading into the server.
can you help me on this where is the bug ?

**Comment by allanbowe** [comment]
@shivakrishnay  - you are right, the advice above does not seem to work - I have actually been unable to find the setting that enables >100mb uploads, at least in Viya 3.5 (I tried several places)

We have decided to implement a workaround, as follows (this will also benefit users who are unable to change admin settings):

* Large files will be chunked into 75mb sections
* Each section will be uploaded in series and appended using [mp_binarycopy](https://core.sasjs.io/mp__binarycopy_8sas.html)
* A progress indicator will be shown

@sabhas  is picking this up.
